# Generated by Django 5.2.7 on 2026-03-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('us_id', models.AutoField(primary_key=True, serialize=False)),
                ('us_firstname', models.CharField(max_length=255)),
                ('us_lastname', models.CharField(max_length=255)),
                ('us_username', models.CharField(max_length=255, unique=True)),
                ('us_password', models.CharField(max_length=255)),
                ('us_age', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
