# Generated by Django 5.2.7 on 2026-03-25 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('bk_id', models.AutoField(primary_key=True, serialize=False)),
                ('bk_name', models.CharField(max_length=255, unique=True)),
                ('bk_address', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'bank',
            },
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('dg_id', models.AutoField(primary_key=True, serialize=False)),
                ('dg_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'degree',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dp_id', models.AutoField(primary_key=True, serialize=False)),
                ('dp_address', models.CharField(max_length=255, null=True)),
                ('dp_classAmount', models.PositiveIntegerField()),
                ('dp_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inv_id', models.AutoField(primary_key=True, serialize=False)),
                ('inv_bookname', models.CharField(max_length=255, unique=True)),
                ('inv_bookamount', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('st_nationalid', models.AutoField(primary_key=True, serialize=False)),
                ('st_firstname', models.CharField(max_length=255)),
                ('st_lastname', models.CharField(max_length=255)),
                ('st_age', models.PositiveSmallIntegerField()),
                ('st_gender', models.BooleanField()),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='us_age',
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('ad_id', models.AutoField(primary_key=True, serialize=False)),
                ('us_id', models.ForeignKey(db_column='us_id', on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('cq_id', models.AutoField(primary_key=True, serialize=False)),
                ('cq_number', models.IntegerField(null=True)),
                ('cq_owner', models.CharField(max_length=255)),
                ('cq_bankname', models.ForeignKey(db_column='bk_id', default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.bank')),
            ],
            options={
                'db_table': 'cheque',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('cl_id', models.AutoField(primary_key=True, serialize=False)),
                ('cl_fee', models.PositiveBigIntegerField()),
                ('dp_id', models.ForeignKey(db_column='dp_id', default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.department')),
            ],
            options={
                'db_table': 'class',
            },
        ),
        migrations.CreateModel(
            name='BookRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cl_id', models.ForeignKey(db_column='cl_id', on_delete=django.db.models.deletion.CASCADE, to='core.class')),
                ('inv_id', models.ForeignKey(db_column='inv_id', on_delete=django.db.models.deletion.CASCADE, to='core.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('mg_id', models.AutoField(primary_key=True, serialize=False)),
                ('us_id', models.ForeignKey(db_column='us_id', on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
            options={
                'db_table': 'manager',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('pay_id', models.AutoField(primary_key=True, serialize=False)),
                ('pay_amount', models.PositiveIntegerField(default=0)),
                ('pay_method', models.CharField(max_length=100)),
                ('pay_date', models.DateTimeField(auto_now_add=True)),
                ('cq_id', models.ForeignKey(db_column='cq_id', on_delete=django.db.models.deletion.CASCADE, to='core.cheque')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('rg_id', models.AutoField(primary_key=True, serialize=False)),
                ('rg_date', models.DateTimeField(auto_now_add=True)),
                ('cl_id', models.ForeignKey(db_column='cl_id', on_delete=django.db.models.deletion.CASCADE, to='core.class')),
                ('pay_id', models.ForeignKey(db_column='pay_id', on_delete=django.db.models.deletion.CASCADE, to='core.payment')),
                ('st_id', models.ForeignKey(db_column='st_id', on_delete=django.db.models.deletion.CASCADE, to='core.student')),
            ],
            options={
                'db_table': 'register',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('th_id', models.AutoField(primary_key=True, serialize=False)),
                ('th_firstname', models.CharField(max_length=255)),
                ('th_lastname', models.CharField(max_length=255)),
                ('dg_id', models.ForeignKey(db_column='dg_id', default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.degree')),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
        migrations.AddField(
            model_name='class',
            name='th_id',
            field=models.ForeignKey(db_column='th_id', default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.teacher'),
        ),
    ]
