# Generated by Django 5.2.7 on 2026-03-25 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bank_degree_department_inventory_student_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='th_id',
            new_name='th_nationalid',
        ),
    ]
