# Generated by Django 5.2.7 on 2026-03-25 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_th_id_teacher_th_nationalid'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookrequirements',
            table='bookrequirements',
        ),
    ]
